### ISSUE TITLE
Better stack traces

### ISSUE THREAD

**Issue by DanL0** [evmts/tevm-cast#5]
Is it possible to achieve level --trace for cast call equivalent to cast call --trace in Foundry?

**Comment by roninjin10** [comment]
Absolutely! The [tracing logic is in CallHandler class](https://github.com/evmts/tevm-cast/blob/main/src/CallHandler.ts#L131) 

To implement this we can do following

- [ ] Update the [rendering logic in Html class](https://github.com/evmts/tevm-cast/blob/main/src/Html.ts#L25) to extract the trace if it exists and render the correct html

**Comment by roninjin10** [comment]
Gonna give this a shot today

**Comment by roninjin10** [comment]
Feature has been implemented. Like and retweet to promote if you get a chance @DanL0 :) 

https://x.com/FUCORY/status/1843764993466216701
